---
- include: ipaddr.yml

- name: delete previous containers if any
  shell: ./remove.sh swarmworker >> remove.log
  args:
    chdir: /vagrant/
    executable: /bin/bash

- name: create the swarm worker
  command: docker run -d --name swarmworker swarm join --advertise={{ my_ip_address.stdout }}:2375 consul://{{ consul0_ip_address.stdout }}:8500
