version: '2'
services:
  web-app:
    build: ./web-app
    ports:
      - "8080:8080"
    logging:
      driver: fluentd
    depends_on:
      - fluentd
  fluentd:
    image: fluent/fluentd
    ports:
      - "24224:24224"
    volumes:
      - /data:/fluentd/log
      - ./fluentd:/fluentd/etc/
    environment:
      - FLUENTD_CONF=in_docker.conf
