version: '2'
services:
  kibana:
    image: kibana:4.6
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - "9200:9200"
    depends_on:
      - fluentd
  fluentd:
    build: fluentd/
    ports:
      - "24224:24224"
