version: '2'
services:
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    depends_on:
      - fluentd
  fluentd:
    image: fluent/fluentd
    ports:
      - "24224:24224"
    volumes:
      - /tmp:/fluentd/log
    environment:
      - FLUENTD_CONF=fluent.conf
