---
- name: setup consul daemon

  # name of the host to run this on.
  hosts: discovery
  vars:

    # execute all commands as root
    ansible_become_user: root
    ansible_become_method: sudo
    ansible_become: true

  roles:
  - setup_discovery
