---
- name: setup docker on all nodes
  # name of the host to run this on.
  hosts: docker
  vars:

    # execute all commands as root
    ansible_become_user: root
    ansible_become_method: sudo
    ansible_become: true

  roles:
  - install_docker
